backend:
  name: git-gateway
  branch: master

site_url: https://confident-archimedes-ed555e.netlify.com/

publish_mode: editorial_workflow

media_folder: static/img
public_folder: /img

collections:
  - name: 'quiz'
    label: 'Quizzes'
    label_singular: 'Quiz'
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines that are specific to a collection.
    folder: "src/pages/quiz"
    create: true
    slug: "{{slug}}"
    preview_path: quiz/{{slug}}
    fields:
      - { label: Template Key, name: templateKey, widget: hidden, default: QuizController }
      - { label: Title, name: title, widget: string }
      - label: 'SiteMetadata'
        name: 'siteMetadta'
        widget: 'object'
        fields: 
          - { label: Description, name: description, widget: text }
          - { label: ShareImage, name: shareImage, widget: image }
      - label: 'Splash'
        name: 'splash'
        widget: 'object'
        fields:
          - { label: Header, name: header, widget: string }
          - { label: Intro, name: body, widget: markdown }
          - label: 'HeaderCTA'
            name: 'headercta'
            widget: 'object'
            fields:
              - { label: Text, name: text, widget: string, default: Donate }
              - { label: URL, name: url, widget: string, default: https://give.thetrevorproject.org/give/63307/#!/donation/checkout }
          - { label: EmailRequired, name: emailRequired, widget: boolean, default: true, hint: Default is True }
          - { label: BackgroundImage, name: backgroundImage, widget: image }
          - { label: ButtonText, name: buttonText, widget: string }
      - label: 'Questions'
        name: 'questions'
        widget: 'object'
        fields: 
          - { label: BackgroundImage, name: backgroundImage, widget: image, default: /img/backgroundStar.png }
          - { label: QuestionValue, name: questionvalue, widget: number, valueType: int, min: 1, max: 1000, hint: Value is set in cents. For example (100 will result in $1.00 per question)., required: false }
          - label: 'Question'
            name: 'question'
            widget: 'list'
            fields:
              - { label: QuestionText, name: questiontext, widget: text }
              - { label: QuestionImage, name: questionimage, widget: image, hint: Used when viewport is 768px wide or greater., required: false }
              - { label: QuestionImageMobile, name: questionimagemobile, widget: image, hint: Used when viewport is smaller than 768px wide., required: false }
              - label: 'Options'
                name: 'options'
                widget: 'list'
                hint: 'Minimun required 2 options and a Maximun of 4 options'
                fields:
                  - { label: OptionText, name: optiontext, widget: string }
                  - { label: IsCorrect, name: iscorrect, widget: boolean, default: false }
              - label: 'Answers'
                name: 'answers'
                widget: 'object'
                fields:
                  - { label: CorrectAnswer, name: correctanswer, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}]}
                  - { label: IncorrectAnswer, name: incorrectanswer, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}]}
                  - { label: AnswerImage, name: answerimage, widget: image, hint: Used when viewport is 768px wide or greater., required: false }
                  - { label: AnswerImageMobile, name: answerimagemobile, widget: image, hint: Used when viewport is smaller than 768px wide., required: false }
      - label: 'ResultsPage'
        name: 'resultspage'
        widget: 'object'
        fields: 
          - { label: Outro, name: body, widget: markdown }
          - { label: BackgroundImage, name: backgroundImage, widget: image }
          - label: 'CTA'
            name: 'cta'
            widget: 'object'
            fields:
              - { label: Text, name: text, widget: string, default: Donate }
              - { label: URL, name: url, widget: string, default: https://give.thetrevorproject.org/give/63307/#!/donation/checkout }